# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- id: kubeker
  main: ./cmd/kubeker
  binary: kubeker
  env:
  - CGO_ENABLED=0
- id: kubekerd
  main: ./cmd/kubekerd
  binary: kubekerd
  env:
  - CGO_ENABLED=0


archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
