# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- id: doker
  main: ./cmd/doker
  binary: doker
  env:
  - CGO_ENABLED=0

archives:
- builds:
  id: doker-binary
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: false
  format: binary
- builds:
  id: doker-tar
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - none*'