name: release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:10}
    - name: Docker PKG Registry Login
      run:
        docker login --username ${{ secrets.username}} --password ${{secrets.password}}
    - name: Building Docker Image
      env :
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        CONTAINER_IMAGE_NAME: tarunpothulapati/kubekerd
      run:
        docker build -t $CONTAINER_IMAGE_NAME:$RELEASE_VERSION .
    - name: Pushing Image to Github Packages
      env :
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        CONTAINER_IMAGE_NAME: tarunpothulapati/kubekerd
      run:
        docker push $CONTAINER_IMAGE_NAME:$RELEASE_VERSION
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
